title:             Random Thoughts About Software Development and Cyber Security
email:             your-email@example.com
description:       My views on software and cyber security
author:            Olivier Vaillancourt
baseurl:           "/startbootstrap-clean-blog-jekyll"
url:               "http://blackrockdigital.github.io"

# Social Profiles
twitter_username:  olivaillancourt
github_username:   oliviervaillancourt

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
